### ISSUE TITLE
How about the cmbat rate？ 100% win really？😄

### ISSUE THREAD

**Issue by ChenYCL** [PHANzgz/CryptoBlades-calculator#1]

**Comment by PHANzgz** [comment]
haha well, if you're patient and wait for the correct opponent to show up it's basically 100% guaranteed. I think they refresh every hour or so.

If you have the trait advantage and that enemy gives you 28 or 29 EXP is a 100% probability

**Comment by ChenYCL** [comment]
i have a advance idea,when i get the best rate ,i'll  mock a click action on card, but the difficulty is that metamask cannot be controlled,like click  confirm button

**Comment by PHANzgz** [comment]
That could be very dangerous. I would recommend against automating Metamask transactions.
