### ISSUE TITLE
actual game does not work since today update

### ISSUE THREAD

**Issue by lokus77** [PHANzgz/CryptoBlades-calculator#5]
Button have error:
userscript.html?name=CryptoBlades%20Fight%20Probability%20Calculator.user.js&id=8880598a-043c-4b35-bf95-1a9c82000767:10430 Uncaught TypeError: **Cannot read property 'className' of null**
    at HTMLButtonElement.eval (userscript.html?... etc

**Comment by PHANzgz** [comment]
Just merged a new PR that solves the issue, should be working fine now.

**Comment by PHANzgz** [comment]
Thanks for the feedback
